### ISSUE TITLE
Does not work on Sway

### ISSUE THREAD

**Issue by Familex** [Jappie3/wayfreeze#12]
I use current version from nixpkgs-unstable (0.1.0).

The screen don't freeze then stating the program (I type just `wayfreeze`). And it not capture mouse/keyboard.

I built 0ff0e9a1ebb617c5bcf980e81d6309e80a4880ac version and it works as expected...

**Comment by Jappie3** [comment]
we are in the process of getting the nixpkgs version up to date (see https://github.com/NixOS/nixpkgs/pull/343515)
the issue of not working on Sway has indeed been dealt with, but it's just not yet upstreamed
