### ISSUE TITLE
manual build instructions?

### ISSUE THREAD

**Issue by MRSS02** [Jappie3/wayfreeze#5]
Hi, is there a way to add in the readme instructions to build this tool manually for those who don't use nix?

**Comment by Jappie3** [comment]
First, make sure you have Rust & Cargo installed. Then clone this repo & run `cargo build --release` in the root, the compiled binary should be under `./target/release/wayfreeze`.

**Comment by Jappie3** [comment]
should be fixed in 9a20eb96be061783309942632caf801eac0c36f6, lmk if you have any other questions ^^
