### ISSUE TITLE
Double dimming in windows when using alongsde grim + slurp in sway / swayFX

### ISSUE THREAD

**Issue by MRSS02** [Jappie3/wayfreeze#7]
i started noticing afterwards that for some reason with a command like `$(grim -g "$(slurp -d -c "#33bbffee" -b "#10101070" -s "#00000000" -F 'Fira Sans' -w 2)" - | wl-copy; killall wayfreeze) & sleep .1; wayfreeze --hide-cursor`, sometimes it is evoking the grim dim screen effect twice, which makes the screenshots also contain that dim. Can this be solved?

https://github.com/user-attachments/assets/fb159b45-a42f-4cb8-b937-efdbbfb2fb89

_Originally posted by @MRSS02 in https://github.com/Jappie3/wayfreeze/issues/6#issuecomment-2266355233_

**Comment by Jappie3** [comment]
I'm working on a better solution than the bash command, I'll let you know when there's something to test
