### ISSUE TITLE
aur?

### ISSUE THREAD

**Issue by littleblack111** [Jappie3/wayfreeze#9]

**Comment by Jappie3** [comment]
I don't use Arch myself so I'm not gonna package & maintain it, sorry
Building should be as simple as running `cargo build` - feel free to package it & open a PR if you want to put it in the readme

**Comment by littleblack111** [comment]
> I don't use Arch myself so I'm not gonna package & maintain it, sorry
> 
> Building should be as simple as running `cargo build` - feel free to package it & open a PR if you want to put it in the readme

Alright! I'll have a go on putting it on the aur

**Comment by Jappie3** [comment]
oh that's been in the back of my head for a while now... very much appreciated, thanks!

**Comment by matejdro** [comment]
there is an AUR package now: https://aur.archlinux.org/packages/wayfreeze-git

**Comment by Jappie3** [comment]
oh nice! then ig this can be closed for now

**Comment by Jappie3** [comment]
when I update the readme for #13 i'll also mention the AUR package
